In [1]:
import numpy as np

In [2]:
# 1. Create a 1D array of numbers from 0 to 9.
x = np.arange(0,10)
print('x: \n',x)
print('\ndimension of the array: \n',x.ndim)

x: 
 [0 1 2 3 4 5 6 7 8 9]

dimension of the array: 
 1


In [3]:
# 2. Create a 3×3 numpy array of all True’s
x = np.ones(shape = (3,3), dtype = bool)
print(x)
print('\nshape of the array x: \n', x.shape)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

shape of the array x: 
 (3, 3)


In [14]:
# 3. Given an array as input, print only odd numbers as output
x = np.array([[2,3,4,8],[5,6,7,10],[12,14,13,15]])
print('x: \n',x)
print('\nodd numbers in the array are: \n', x[x%2!=0])
# 4. Replace all odd numbers in arr with -2
x[x%2!=0] = -2
print('\n replace all odd numbers with -2: \n', x)

x: 
 [[ 2  3  4  8]
 [ 5  6  7 10]
 [12 14 13 15]]

odd numbers in the array are: 
 [ 3  5  7 13 15]

 replace all odd numbers with -2: 
 [[ 2 -2  4  8]
 [-2  6 -2 10]
 [12 14 -2 -2]]


In [5]:
# 5. How to reshape an array?
x = np.ones(shape = (4,4))
print('original array x: \n',x)
print('\nshape of the original array x: \n', x.shape)
y=x.reshape(8,2)
print('\nafter reshape: \n', y)
print('\n shape of the rehsaped array: \n', y.shape)

original array x: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

shape of the original array x: 
 (4, 4)

after reshape: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 shape of the rehsaped array: 
 (8, 2)


In [6]:
# 6. Convert a 1D array to a 2D array with 2 rows
x = np.arange(0,8)
print('1d array x: \n', x)
print('\ndimension of the array: \n', x.ndim)
print('\nshape of the array x: \n', x.shape)
y = x.reshape(2,4)
print('\n 2d array with 2 rows: \n', y)
print('\n dimension of the new array with 2 rows: \n', y.ndim)

1d array x: 
 [0 1 2 3 4 5 6 7]

dimension of the array: 
 1

shape of the array x: 
 (8,)

 2d array with 2 rows: 
 [[0 1 2 3]
 [4 5 6 7]]

 dimension of the new array with 2 rows: 
 2


In [7]:
# 7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , 
# create  new array b from a such that b includes all odd numbers and 4 multiples. 
a = np.array([1,2,3,4,5,6,7,8,9])
print('a: \n', a)
a1 = a[a%2 != 0]
print('\narray with all odd numbers: \n', a1)
a2 = a[a%4 == 0]
print('\narray with 4 multiples: \n', a2)
b = np.union1d(a1,a2)
print('\narray with odd numbers and 4 multiples: \n', b)

a: 
 [1 2 3 4 5 6 7 8 9]

array with all odd numbers: 
 [1 3 5 7 9]

array with 4 multiples: 
 [4 8]

array with odd numbers and 4 multiples: 
 [1 3 4 5 7 8 9]


In [8]:
# 8. Given array, check if there are any null values and print them out. 
x = np.array([[1,2,np.nan], [4,np.nan,7]])
print('x: \n',x)
print('\ndoes x has any null values?: \n', np.isnan(x))
print('\nnull values in x: \n', x[np.isnan(x)])

# 9. How to replace all missing values with 0 in a numpy array?
x[np.isnan(x)] = 0
print('replacing all missing values with 0: \n', x)

x: 
 [[ 1.  2. nan]
 [ 4. nan  7.]]

does x has any null values?: 
 [[False False  True]
 [False  True False]]

null values in x: 
 [nan nan]
replacing all missing values with 0: 
 [[1. 2. 0.]
 [4. 0. 7.]]


In [9]:
# 10. How to find the count of each unique number in a NumPy array?
x = np.array([[[33,44,33,55,22],[11,66,22,88,99]],[[11,66,22,99,100],[99,55,77,11,22]]])
print('x: \n', x)
print('\nunique elements of the array are: \n', np.unique(x, return_counts=True))

x: 
 [[[ 33  44  33  55  22]
  [ 11  66  22  88  99]]

 [[ 11  66  22  99 100]
  [ 99  55  77  11  22]]]

unique elements of the array are: 
 (array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 100]), array([3, 4, 2, 1, 2, 2, 1, 1, 3, 1], dtype=int64))


In [59]:
# 11. How to convert a numeric to a categorical (text) array?
x = np.array([[4,5,6],[33,21,47],[87,54,60]], dtype = 'int32')
print('x: \n', x)
y = x.astype('str')
print('y: \n', y)
print(y.dtype)

x: 
 [[ 4  5  6]
 [33 21 47]
 [87 54 60]]
y: 
 [['4' '5' '6']
 ['33' '21' '47']
 ['87' '54' '60']]
<U11


In [11]:
# 12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both.
x = np.arange(99,299)
a = x[x%5 == 0]
b = x[x%7 == 0]
c = np.setxor1d(a,b)
print('original array x: \n',x)
print('\nnumbers divisible by 5: \n',a)
print('\n numbers divisible by 7: \n',b)
print('\n numbers divisible by 5 or 7 but not both: \n', c)

original array x: 
 [ 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278
 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296
 297 298]

numbers divisible by 5: 
 [100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265 27

In [60]:
# 12. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
x = np.arange(10,100,5)
print('original array x: \n', x)
print('\nreversed array: \n', x[::-1])

original array x: 
 [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

reversed array: 
 [95 90 85 80 75 70 65 60 55 50 45 40 35 30 25 20 15 10]
